### PR TITLE
Sugar

### PR DESCRIPTION
**Pull request by jbrumwell**
Almost got it but some reason its feed back your commits that you've already done. The last commit is the only one that needs to be merged that updates the test file and sanitize.js

### CODE REVIEW

**Comment by buschtoens** [comment]
[Pulling in Upstream Changes](https://help.github.com/articles/fork-a-repo). Should be helpful. :)

Thanks for fixing my mess and providing the tests, you busy bee. :wink:

**Comment by jbrumwell** [comment]
ahh maybe that's what I did wrong the tutorial I read said to:

`git rebase upstream/master`

but from your link it seems I should have

`git merge upstream/master`

Thanks & np!

**Comment by buschtoens** [comment]
I'll revert my last commit trying to merge your PR (because I obviously failed) and you try to file a correct PR? :D

**Comment by buschtoens** [comment]
Seems like I didn't fail that hard. Fixed it.
Do you still want to redo your PR?

(There are [some test cases failing](https://travis-ci.org/silvinci/node-sanitize-arguments/jobs/3143218). I'll investigate.)

**Comment by buschtoens** [comment]
Aha, you [missed a line](https://github.com/silvinci/node-sanitize-arguments/commit/99acc32257be08b3d5ef85496af51b7d71f5e212#L0L45).

**Comment by buschtoens** [comment]
[Shazam!](https://travis-ci.org/silvinci/node-sanitize-arguments/jobs/3143280)

(Still open for remerging your PR, if you want to)

**Comment by jbrumwell** [comment]
Nah I'm good glad it passes!

**Comment by buschtoens** [comment]
I did some quick tests and everything works just fine.
Sanitize 2.0  [is released](https://npmjs.org/package/sanitize-arguments).

**Pull request closed without merging**
