### PR TITLE
Allow for default values

### PR DESCRIPTION
**Pull request by jbrumwell**
This will allow for default argument values

example:

``` js
function F(path, options, cb) {
    sanitize(arguments, F, [String, Object, {type: Function, default: function() {}}]);
}
```

### CODE REVIEW

**Comment by buschtoens** [comment]
LGTM. Thanks.

I'll add some comments, docs and tests in a few hours. The new version will then syndicate to npm.

**Comment by buschtoens** [comment]
The only problem I see are custom classes, that have `type` and `default` attribute/method in their prototype.

Maybe the syntax should be changed to `sanitize(arguments, F, [Number, String], [null, "Hello"])`.  
Additionally it wouldn't be that lengthy.

**Comment by jbrumwell** [comment]
It will only initialize if the typeof the value is Object, for all types it should be Function is checked for within your code, so the following;

var foo = function() {};
foo.type = Function;
foo.default = 'default';

wouldn't work because the typeOf would return Function and not Object. I'm not a fan of the 4th parameter because if you only want to default the last parameter your going to end up with [undefined, undefined, undefined, function() {}] if were only going to deal with the default value and not add any other options like validation for when two arguments are the same type or something else.. then this may work

`sanitize(arguments, F, [ [Number, 0], [String, 'here'] ])`

Then change the tests to look for an Array instead of an Object. What are your thoughts?

**Comment by buschtoens** [comment]
Ah, yep. Forgot my own API. Haha.

Your format looks very good. But I'd make The default parameter optional. Just like so:

`sanitize(arguments, F, [ Number, [String, "Meow"], Function ])`

Do you want to PR or shall I do it in a few hours?

**Comment by buschtoens** [comment]
#10

**Pull request merged**
